In [2]:
w1, w2, w3 = 0.3, 0.2, 0.5

In [3]:
import pandas as pd

In [4]:
df = pd.DataFrame({
    "Region": ["Kanto","Johto","Hoenn","Sinnoh","Unova"],
    "Temp": [73,91,87,102,69],
    "Rainfall": [67,88,134,43,96],
    "Humidity": [43,64,58,37,70]
})


In [5]:
ktemp = df["Temp"].values[0]
krainfall = df["Rainfall"].values[0]
khumidity = df["Humidity"].values[0]

In [6]:
kanto_yield_apples = ktemp*w1+krainfall*w2+khumidity*w3
kanto_yield_apples

np.float64(56.8)

In [7]:
kanto = [73, 67, 43]
johto = [91, 88, 64]
hoenn = [87, 134, 58]
sinnoh = [102, 43, 37]
unova = [69, 96, 70]
regions = [kanto, johto, hoenn, unova]

In [8]:
weights = [w1, w2, w3]

In [9]:
def crop_yield(region, weights):
    result = 0
    for x,w in zip(region, weights):
        result += x*w
    return result

In [10]:
crop_yield(kanto, weights)

56.8

In [11]:
zip?

Init signature: zip(*iterables, strict=False)
Docstring:     
The zip object yields n-length tuples, where n is the number of iterables
passed as positional arguments to zip().  The i-th element in every tuple
comes from the i-th iterable argument to zip().  This continues until the
shortest argument is exhausted.

If strict is true and one of the arguments is exhausted before the others,
raise a ValueError.

   >>> list(zip('abcdefg', range(3), range(4)))
   [('a', 0, 0), ('b', 1, 1), ('c', 2, 2)]
Type:           type
Subclasses:     

In [12]:
import numpy as np

In [13]:
regions

[[73, 67, 43], [91, 88, 64], [87, 134, 58], [69, 96, 70]]

In [14]:
region_names = ['Kanto', 'Johto', 'Hoenn', 'Sinnoh', 'Unova']

In [15]:
weights = np.array([0.3,0.2,0.5])

In [16]:
kanto = np.array([73, 67, 43])

In [17]:
johto = np.array([91, 88, 64])

In [18]:
hoenn = np.array([87,134,58])

In [19]:
sinnoh = np.array([102, 43, 37])

In [20]:
unova = np.array([69, 96, 70])

In [21]:
type(kanto)

numpy.ndarray

In [22]:
weights[0]

np.float64(0.3)

In [23]:
kanto[0]

np.int64(73)

In [24]:
help(np.dot)

Help on _ArrayFunctionDispatcher in module numpy:

dot(...)
    dot(a, b, out=None)

    Dot product of two arrays. Specifically,

    - If both `a` and `b` are 1-D arrays, it is inner product of vectors
      (without complex conjugation).

    - If both `a` and `b` are 2-D arrays, it is matrix multiplication,
      but using :func:`matmul` or ``a @ b`` is preferred.

    - If either `a` or `b` is 0-D (scalar), it is equivalent to
      :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
      preferred.

    - If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
      the last axis of `a` and `b`.

    - If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
      sum product over the last axis of `a` and the second-to-last axis of
      `b`::

        dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

    It uses an optimized BLAS library when possible (see `numpy.linalg`).

    Parameters
    ----------
    a : array_like
        Fir

In [25]:
np.dot(kanto, weights)

np.float64(56.8)

In [26]:
(weights*kanto).sum()

np.float64(56.8)

In [27]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

(arr1*arr2).sum()

np.int64(32)

In [28]:
arr1 = list(range(1000000))
arr2 = list(range(1000000, 2000000))

arr1_np = np.array(arr1)
arr2_np = np.array(arr2)

In [29]:
%%time

result = 0

for x1, x2 in zip(arr1, arr2):
    result += x1*x2

result

CPU times: total: 672 ms
Wall time: 684 ms


833332333333500000

In [30]:
%%time
np.dot(arr1_np, arr2_np)

CPU times: total: 0 ns
Wall time: 4.58 ms


np.int64(833332333333500000)

In [31]:
climate_data = np.array([[73,67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69,96,70]])

climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [32]:
climate_data.shape

(5, 3)

In [33]:
weights

array([0.3, 0.2, 0.5])

In [34]:
weights.shape

(3,)

In [35]:
arr3 = np.array([
    [[1,2,3],
     [4,5,6]],
    [[7,8,9],
     [10,11,12]]
])

In [36]:
arr3.shape

(2, 2, 3)

In [37]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [38]:
weights.dtype

dtype('float64')

In [39]:
climate_data.dtype

dtype('int64')

In [40]:
arr3.dtype

dtype('int64')

In [41]:
np.matmul?

Signature:       np.matmul(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'matmul'>
File:            c:\users\ansh\appdata\local\programs\python\python313\lib\site-packages\numpy\__init__.py
Docstring:      
matmul(x1, x2, /, out=None, *, casting='same_kind', order='K', dtype=None, subok=True[, signature, axes, axis])

Matrix product of two arrays.

Parameters
----------
x1, x2 : array_like
    Input arrays, scalars not allowed.
out : ndarray, optional
    A location into which the result is stored. If provided, it must have
    a shape that matches the signature `(n,k),(k,m)->(n,m)`. If not
    provided or None, a freshly-allocated array is returned.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
y : ndarray
    The matrix product of the inputs.
    This is a scalar only when both x1, x2 are 1-d vectors.

Raises
------
ValueError
    If the last dimension of `x1` is not the same size as
    the second-to-

In [42]:
np.matmul(climate_data,weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [43]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [44]:
pip install opendatasets


Note: you may need to restart the kernel to use updated packages.


In [47]:
np.zeros((999,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [0., 0.]], shape=(999, 2))

In [49]:
np.ones([4,25,3,8,4,6,3,6])

array([[[[[[[[1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.]],

            [[1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.]],

            [[1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.]],

            [[1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.]],

            [[1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.]],

            [[1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.]]],


           [[[1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.]],

            [[1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.],
             [1., 1., 1., 1., 1., 1.]],

            [[1., 1., 1., 1., 1., 1.],
       

In [55]:
np.random.rand(5)

array([0.35632603, 0.93852711, 0.29525013, 0.45099697, 0.94523013])

In [61]:
np.random.randn(2,3,4,5)

array([[[[-0.41120427,  1.64024098, -0.11571731, -0.66025176,
           0.12816708],
         [-1.27232265,  0.8379617 ,  0.8253663 , -0.21155421,
           1.00086396],
         [ 0.93210244, -1.01938397, -0.99927053,  0.09472999,
          -1.07000318],
         [ 1.11177891,  0.52181865, -1.91341184,  0.86371315,
           1.16883357]],

        [[-0.42473298, -0.01777033, -1.71415894,  0.06212634,
          -0.46440169],
         [-0.29729294, -0.80736005,  0.45750455, -0.55686789,
           0.3014156 ],
         [ 0.3532072 ,  0.1071111 , -0.04552322,  1.27116943,
           0.74412881],
         [-0.89893789,  0.36545204, -0.36852831, -1.19037924,
           0.62873203]],

        [[ 0.656907  , -0.68761263,  1.24102848, -1.65713334,
          -0.40700093],
         [-0.04513815, -0.13698873,  0.15162166,  1.30265485,
           0.60219278],
         [-0.95626795,  0.3398385 ,  0.05251317, -1.47698339,
          -0.24897523],
         [-1.21908829,  0.95376377,  1.01397741, -

In [60]:
np.full((2,3), 42)

array([[42, 42, 42],
       [42, 42, 42]])

In [65]:
a = np.arange(4, 3482, 200)

In [66]:
for i in a:
    print(i)

4
204
404
604
804
1004
1204
1404
1604
1804
2004
2204
2404
2604
2804
3004
3204
3404


In [69]:
a.reshape(9,2)

array([[   4,  204],
       [ 404,  604],
       [ 804, 1004],
       [1204, 1404],
       [1604, 1804],
       [2004, 2204],
       [2404, 2604],
       [2804, 3004],
       [3204, 3404]])

In [70]:
np.linspace??

Signature:      
np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    axis=0,
    *,
    device=None,
)
Call signature:  np.linspace(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function linspace at 0x000001B1E86F7740>
File:            c:\users\ansh\appdata\local\programs\python\python313\lib\site-packages\numpy\_core\function_base.py
Source:         
@array_function_dispatch(_linspace_dispatcher)
def linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
             axis=0, *, device=None):
    """
    Return evenly spaced numbers over a specified interval.

    Returns `num` evenly spaced samples, calculated over the
    interval [`start`, `stop`].

    The endpoint of the interval can optionally be excluded.

    .. versionchanged:: 1.20.0
        Values are rounded towards ``-inf`` instead of ``0`` when an
        integer ``dtype`` is specified. The old behavior can
        still be

In [72]:
np.linspace(3, 27, 94)

array([ 3.        ,  3.25806452,  3.51612903,  3.77419355,  4.03225806,
        4.29032258,  4.5483871 ,  4.80645161,  5.06451613,  5.32258065,
        5.58064516,  5.83870968,  6.09677419,  6.35483871,  6.61290323,
        6.87096774,  7.12903226,  7.38709677,  7.64516129,  7.90322581,
        8.16129032,  8.41935484,  8.67741935,  8.93548387,  9.19354839,
        9.4516129 ,  9.70967742,  9.96774194, 10.22580645, 10.48387097,
       10.74193548, 11.        , 11.25806452, 11.51612903, 11.77419355,
       12.03225806, 12.29032258, 12.5483871 , 12.80645161, 13.06451613,
       13.32258065, 13.58064516, 13.83870968, 14.09677419, 14.35483871,
       14.61290323, 14.87096774, 15.12903226, 15.38709677, 15.64516129,
       15.90322581, 16.16129032, 16.41935484, 16.67741935, 16.93548387,
       17.19354839, 17.4516129 , 17.70967742, 17.96774194, 18.22580645,
       18.48387097, 18.74193548, 19.        , 19.25806452, 19.51612903,
       19.77419355, 20.03225806, 20.29032258, 20.5483871 , 20.80