In [3]:
# 🧠 NumPy Practice Problem 1 (Easy):
# Create a 1D NumPy array of integers from 0 to 9. Then, square each element and print the resulting array.

# Requirements:

# Use np.arange() or any method to create the initial array.

# Square the values using NumPy (avoid loops).

In [4]:
import numpy as np

In [5]:
np.arange??

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

In [6]:
array = np.arange(0,10,1)
squared_array = np.power(array, 2)
print(squared_array)

[ 0  1  4  9 16 25 36 49 64 81]


In [7]:
# 🔢 NumPy Practice Problem 2 (Easy-Medium):
# Create a 3x3 NumPy array with values from 1 to 9 (inclusive). Then, calculate:

# The sum of all elements.

# The sum of each row.

# The sum of each column.

In [8]:
import numpy as np

array = np.arange(1, 10).reshape(3, 3)
print(array)

total = np.sum(array)
print("Total sum:", total)

row_sums = np.sum(array, axis=1)
print("Row sums:", row_sums)

col_sums = np.sum(array, axis=0)
print("Column sums:", col_sums)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
Total sum: 45
Row sums: [ 6 15 24]
Column sums: [12 15 18]


In [9]:
# 🧪 NumPy Practice Problem 3 (Medium):
# Create a 5×5 identity matrix and multiply it by a 5×5 matrix filled with the number 7. What do you expect the result to be?

# Then, print the resulting matrix and verify if your prediction was correct.

In [10]:
array = np.identity(5)
array_7 = np.full((5,5), 7)
final_array = array @ array_7
print(final_array)

[[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


In [11]:
np.identity??

Signature: np.identity(n, dtype=None, *, like=None)
Docstring:
Return the identity array.

The identity array is a square array with ones on
the main diagonal.

Parameters
----------
n : int
    Number of rows (and columns) in `n` x `n` output.
dtype : data-type, optional
    Data-type of the output.  Defaults to ``float``.
like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    `n` x `n` array with its main diagonal set to one,
    and all other elements 0.

Examples
--------
>>> import numpy as np
>>> np.identity(3)
array([[1.,  0.,  0.],
       [0.,  1.,  0.],
       [0.,  0.,  1.]])
Source:   
@finalize_array

In [12]:
# Problem 4 (Intermediate):
# Create a 4x4 NumPy array filled with random integers from 10 to 50 (inclusive).

# Then:

# Replace all values greater than 30 with 30.

# Print the original array and the modified array.

In [13]:
arr = np.random.randint(10, 51, size=(4, 4))

for x in range(arr.shape[0]):  
    for y in range(arr.shape[1]):  
        if arr[x][y] > 30:
            arr[x][y] = 30
    
original = np.random.randint(10, 51, size=(4, 4))

print("Original:\n", original)
print("Modified:\n", arr)

Original:
 [[37 17 17 21]
 [34 22 18 28]
 [20 20 43 30]
 [37 17 49 35]]
Modified:
 [[30 30 30 30]
 [25 30 20 30]
 [27 24 23 30]
 [30 25 22 30]]


In [14]:
# Problem 6 (Harder):
# Create a 6×6 NumPy array of random integers from 1 to 100.

# Then:

# Replace all even numbers with 0

# Replace all odd numbers with 1

# Now count how many 1s and 0s are in the array

# Print the modified array and the counts

# This one's all about indexing, slicing, and counting like a NumPy wizard. 🧙‍♂️

# Let me know when you’re done, and we’ll tackle #7 next!

In [25]:
array = np.random.randint(1,101,size=(6,6))

array[array%2==0] = 0
array[array%2!=0] = 1

odd_count = 0
even_count = 0

for x in range(array.shape[0]):
    for y in range(array.shape[1]):
        if array[x][y] == 0:
            even_count+=1
        else:
            odd_count+=1

print(f"Modified Array:\n {array}")
print(f"Even count {even_count}")
print(f"Odd count {odd_count}")

Modified Array:
 [[0 1 1 0 0 0]
 [1 0 1 0 1 0]
 [1 1 1 0 0 0]
 [0 1 0 1 0 1]
 [0 0 0 1 0 1]
 [0 0 0 0 1 0]]
Even count 22
Odd count 14


In [ ]:
# Problem 7 (Hard):
# Create a 6×6 NumPy array filled with random integers from 1 to 100.

# Then:

# Find the maximum value in each row

# Find the index (column) of the max value for each row

# Replace each max value in the array with -1

# Print the modified array

In [34]:
import numpy as np

array = np.random.randint(1, 101, size=(6, 6))
print("Original Array:\n", array)

max_vals = np.max(array, axis=1) 

max_indices = np.argmax(array, axis=1)

for i in range(array.shape[0]):
    array[i, max_indices[i]] = -1

print("\nModified Array:\n", array)


Original Array:
 [[77 63 81 92  6 83]
 [34 45 33 66 10 98]
 [64 79 82 43 79  7]
 [39 14 46 98 91 25]
 [87 74 56 33 58 66]
 [82 68 22 36 83 36]]

Modified Array:
 [[77 63 81 -1  6 83]
 [34 45 33 66 10 -1]
 [64 79 -1 43 79  7]
 [39 14 46 -1 91 25]
 [-1 74 56 33 58 66]
 [82 68 22 36 -1 36]]


In [35]:
np.argmax??

Signature:       np.argmax(a, axis=None, out=None, *, keepdims=<no value>)
Call signature:  np.argmax(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function argmax at 0x000002BB9CBE6FC0>
File:            c:\users\ansh\appdata\local\programs\python\python313\lib\site-packages\numpy\_core\fromnumeric.py
Source:         
@array_function_dispatch(_argmax_dispatcher)
def argmax(a, axis=None, out=None, *, keepdims=np._NoValue):
    """
    Returns the indices of the maximum values along an axis.

    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    keepdims : bool, optional
        If this is set to True, the axes which are reduced are left
        in the result as dim

In [ ]:
# 🧠 Problem 8 (Boss Level):
# You’re going to build a mini game board.

# Create a 10×10 NumPy array filled with 0s

# Randomly place 20 ones (1s) in random positions

# Then, replace every 0 that touches a 1 (up/down/left/right) with a 2 (but not diagonally!)

# Print the final board

In [92]:
import numpy as np

board = np.zeros((10, 10), dtype=int)

ones_placed = 0
while ones_placed < 20:
    x = np.random.randint(0, 10)
    y = np.random.randint(0, 10)
    if board[x, y] == 0:
        board[x, y] = 1
        ones_placed += 1
        
positions = np.argwhere(board == 1)

for (x, y) in positions:
    if x > 0 and board[x-1, y] == 0:
        board[x-1, y] = 2
    if x < board.shape[0] - 1 and board[x+1, y] == 0:
            board[x+1, y] = 2
    if y > 0 and board[x, y-1] == 0:
        board[x, y-1] = 2
    if y < board.shape[1] - 1 and board[x, y+1] == 0:
        board[x, y+1] = 2


print("Final Game Board:\n", board)


Final Game Board:
 [[0 0 2 2 2 1 2 2 0 0]
 [0 2 1 1 1 2 2 1 2 0]
 [2 1 1 2 2 2 1 2 1 2]
 [0 2 2 0 0 0 2 1 2 2]
 [0 0 0 0 0 0 0 2 2 1]
 [0 0 0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 2 2 2 0 2 1 2 2]
 [2 2 1 1 1 2 2 1 1 1]
 [1 2 2 2 1 2 0 2 2 2]]
